name: Randomology

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs: 
  tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Set up system environment
      run: | 
        sudo apt-get update -y
        sudo apt-get install -y ffmpeg
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Setup configurations
      run: |
        cp .env.toml env.toml
    - name: Test with pytest
      run: |
        python3 -m pytest
